services:
  app:
    image: sensor_api:latest
    container_name: sensor-api
    build:
      context: sensor-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  server:
    image: sensor_server:latest
    container_name: sensor-server
    build:
      context: sensor-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - app

  db:
    image: postgres:15-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sensor_api_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: